<?php


$viloyatlar = [
    "Toshkent viloyati" => "toshkent",
    "Toshkent shahri" => "toshkent-shahri",
    "Andijon viloyati" => "andijon",
    "Farg'ona viloyati" => "fargona",
    "Buxoro viloyati" => "buxoro",
    "Jizzax viloyati" => "jizzax",
    "Xorazm viloyati" => "xorazm",
    "Namangan viloyati" => "namangan",
    "Navoiy viloyati" => "navoiy",
    "Qashqadaryo viloyati" => "qashqadaryo",
    "Samarqand viloyati" => "samarqand",
    "Sirdaryo viloyati" => "sirdaryo",
    "Surxondaryo viloyati" => "surxondaryo",
    "Qoraqalpog'iston Respublikasi" => "qoraqalpogiston",
];

$shaxarlar = [
    'fargona' => [
        "Farg'ona shahri" => "fargona-shahri",
        "Marg'ilon shahar" => "margilon-shahar",
        "Beshariq tumani" => "beshariq",
        "Buvayda tumani" => "buvayda",
        "Dang'ara tumani" => "dangara",
        "Farg'ona tumani" => "fargona",
        "Furqat tumani" => "furqat",
        "Oltiariq tumani" => "oltiariq",
        "Quva tumani" => "quva",
        "Rishton tumani" => "rishton",
        "So'x tumani" => "sox",
        "Toshloq tumani" => "toshloq",
        "Uchko'prik tumani" => "uchkoprik",
        "Yozyovon tumani" => "yozyovon",
    ],
    'andijon' => [
        "Andijon shahri" => "andijon-shahri",
        "Andijon tumani" => "andijon",
        "Asaka tumani" => "asaka",
        "Baliqchi tumani" => "baliqchi",
        "Bo'z tumani" => "boz",
        "Buloqboshi tumani" => "buloqboshi",
        "Izboskan tumani" => "izboskan",
        "Jalaquduq tumani" => "jalaquduq",
        "Marhamat tumani" => "marhamat",
        "Oltinko'l tumani" => "oltinkol",
        "Paxtaobod tumani" => "paxtaobod",
        "Shahrixon tumani" => "shahrixon",
        "Xo'jaobod tumani" => "xjaobod",
        "Ulug'nor tumani" => "ulugnor",
    ],
    'buxoro' => [
        "Buxoro shahri" => "buxoro-shahri",
        "Buxoro tumani" => "buxoro",
        "G'ijduvon tumani" => "gijduvon",
        "Jondor tumani" => "jondor",
        "Kogon tumani" => "kogon",
        "Qorako'l tumani" => "qorakol",
        "Qorovulbozor tumani" => "qorovulbozor",
        "Peshku tumani" => "peshku",
        "Romitan tumani" => "romitan",
        "Shofirkon tumani" => "shofirkon",
        "Vobkent tumani" => "vobkent",
    ],
    'jizzax' => [
        "Jizzax shahri" => "jizzax-shahri",
        "Arnasoy tumani" => "arnasoy",
        "Baxmal tumani" => "baxmal",
        "Do'stlik tumani" => "dostlik",
        "Forish tumani" => "forish",
        "G'allaorol tumani" => "gallaorol",
        "G'azalkent tumani" => "gazalkent",
        "Mirzacho'l tumani" => "mirzachol",
        "Paxtakor tumani" => "paxtakor",
        "Yangiobod tumani" => "yangiobod",
        "Zomin tumani" => "zomin",
    ],
    'xorazm' => [
        "Urganch shahri" => "urganch-shahri",
        "Bog'ot tumani" => "bogot",
        "Gurlan tumani" => "gurlan",
        "Hazorasp tumani" => "hazorasp",
        "Xonqa tumani" => "xonqa",
        "Qo'shko'pir tumani" => "qoshkopir",
        "Qorao'zak tumani" => "qoraozak",
        "Shovot tumani" => "shovot",
        "Urganch tumani" => "urganch",
        "Yangiariq tumani" => "yangiariq",
        "Yangibozor tumani" => "yangibozor",
        "Yangixo'ja tumani" => "yangixja",
        "Xiva tumani" => "xiva",
    ],
    'namangan' => [
        "Namangan shahri" => "namangan-shahri",
        "Chortoq tumani" => "chortoq",
        "Chust tumani" => "chust",
        "Kosonsoy tumani" => "kosonsoy",
        "Mingbuloq tumani" => "mingbuloq",
        "Namangan tumani" => "namangan",
        "Norin tumani" => "norin",
        "Pop tumani" => "pop",
        "To'rakurgon tumani" => "torakurgon",
        "Uchqo'rg'on tumani" => "uchqorgon",
        "Uychi tumani" => "uychi",
        "Yangiqo'rg'on tumani" => "yangiqorgon",
    ],
    'navoiy' => [
        "Navoiy shahri" => "navoiy-shahri",
        "Konimex shahri" => "konimex",
        "Navbahor shahri" => "navbahor",
        "Qiziltepa shahri" => "qiziltepa",
        "Zarafshon shahri" => "zarafshon",
        "Navoiy tumani" => "navoiy",
        "Nurota tumani" => "nurota",
        "Tomdi tumani" => "tomdi",
        "Uchquduq tumani" => "uchquduq",
        "Xatirchi tumani" => "xatirchi",
        "Karmana tumani" => "karmana",
    ],
    'qashqadaryo' => [
        "Qarshi shahri" => "qarshi-shahri",
        "Beshkent tumani" => "beshkent",
        "Chiroqchi tumani" => "chiroqchi",
        "Dehqonobod tumani" => "dehqonobod",
        "G'uzor tumani" => "guzor",
        "Kamashi tumani" => "kamashi",
        "Koson tumani" => "koson",
        "Kitob tumani" => "kitob",
        "Mirishkor tumani" => "mirishkor",
        "Muborak tumani" => "muborak",
        "Nishon tumani" => "nishon",
        "Qamashi tumani" => "qamashi",
        "Qarshi tumani" => "qarshi",
        "Shahrisabz tumani" => "shahrisabz",
        "Yakkabog' tumani" => "yakkabog",
        "Yangiobod tumani" => "yangiobod",
        "Yangiyo'l tumani" => "yangiyol",
        "Zomin tumani" => "zomin",
    ],
    'samarqand' => [
        "Samarqand shahri" => "samarqand-shahri",
        "Bulung'ur tumani" => "bulungur",
        "Ishtixon tumani" => "ishtixon",
        "Jomboy tumani" => "jomboy",
        "Kattaqo'rg'on tumani" => "kattaqorgon",
        "Kattaqo'rg'on shahri" => "kattaqorgon-shahri",
        "Koshrabot tumani" => "koshrabot",
        "Narpay tumani" => "narpay",
        "Nurobod tumani" => "nurobod",
        "Oqdaryo tumani" => "oqdaryo",
        "Paxtachi tumani" => "paxtachi",
        "Payariq tumani" => "payariq",
        "Pastdarg'om tumani" => "pastdargom",
        "Samarqand tumani" => "samarqand",
        "Tayloq tumani" => "tayloq",
        "Urgut tumani" => "urgut",
        "Xo'jaobod tumani" => "xjaobod",
        "Nurota tumani" => "nurota",
    ],
    'sirdaryo' => [
        "Guliston shahri" => "guliston-shahri",
        "Boyovut tumani" => "boyovut",
        "Guliston tumani" => "guliston",
        "Mirzaobod tumani" => "mirzaobod",
        "Oqoltin tumani" => "oqoltin",
        "Sayxunobod tumani" => "sayxunobod",
        "Sirdaryo tumani" => "sirdaryo",
        "Sardoba tumani" => "sardoba",
        "Xovos tumani" => "xovos",
    ],
    'surxondaryo' => [
        "Termiz shahri" => "termiz-shahri",
        "Angor tumani" => "angor",
        "Bandixon tumani" => "bandixon",
        "Boysun tumani" => "boysun",
        "Denov tumani" => "denov",
        "Jarqo'rg'on tumani" => "jarqorgon",
        "Jomboy tumani" => "jomboy",
        "Qiziriq tumani" => "qiziriq",
        "Qumqo'rg'on tumani" => "qumqorgon",
        "Muzrabot tumani" => "muzrabot",
        "Oltinsoy tumani" => "oltinsoy",
        "Sariosiyo tumani" => "sariosiyo",
        "Sho'rchi tumani" => "shorchi",
        "Termiz tumani" => "termiz",
        "Uzun tumani" => "uzun",
        "Sherobod tumani" => "sherobod",
        "Shurchi tumani" => "shurchi",
        "Xo'jaobod tumani" => "xjaobod",
    ],
    'toshkent' => [
        "Toshkent shahri" => "toshkent-shahri",
        "Bekobod tumani" => "bekobod",
        "Bo'stonliq tumani" => "bostonliq",
        "Bo'ka tumani" => "boka",
        "Chinoz tumani" => "chinoz",
        "Ohangaron tumani" => "ohangaron",
        "Oqqo'rg'on tumani" => "oqqorgon",
        "Parkent tumani" => "parkent",
        "Piskent tumani" => "piskent",
        "Quyi chirchiq tumani" => "quyi-chirchiq",
        "O'rta Chirchiq tumani" => "orta-chirchiq",
        "Yangiyo'l tumani" => "yangiyol",
        "Yuqori Chirchiq tumani" => "yuqori-chirchiq",
        "Zangiota tumani" => "zangiota",
        "Zafarobod tumani" => "zafarobod",
        "Zarbdor tumani" => "zarbdor",
        "Zomin tumani" => "zomin",
        "Toshkent tumani" => "toshkent",
    ],
    'toshkent-shahri' => [
        "Yunusobod tumani" => "yunusobod",
        "Yakkasaroy tumani" => "yakkasaroy",
        "Yashnobod tumani" => "yashnobod",
        "Chilonzor tumani" => "chilonzor",
        "Mirobod tumani" => "mirobod",
        "Mirzo Ulug'bek tumani" => "mirzo-ulugbek",
        "Sergeli tumani" => "sergeli",
        "Olmazor tumani" => "olmazor",
        "Shayxontohur tumani" => "shayxontohur",
        "Uchtepa tumani" => "uchtepa",
    ],
    'qoraqalpogiston' => [
        "Beruniy tumani" => "beruniy",
        "Qo'ng'irot tumani" => "qongirot",
        "Qorao'zak tumani" => "qoraozak",
        "Qanliko'l tumani" => "qanlikol",
        "Qo'shtepa tumani" => "qoshtepa",
        "Shumanay tumani" => "shumanay",
        "Taxtako'pir tumani" => "taxtakopir",
        "To'rtko'l tumani" => "tortkol",
        "Xo'jayli tumani" => "xjayli",
        "Ellikqal'a tumani" => "ellikqala",
        "Mo'ynoq tumani" => "moynoq",
        "Nukus tumani" => "nukus",
        "Takhtakupir tumani" => "takhtakupir",
    ]
];

$product_edit_keyboard = [
    ['✏️ Sarlavha' , '✏️ Tavsif'],
    ['✏️ Rasm'],
    ["🔙 Orqaga"]
];